server:
  port: 27001

spring:
  application:
    name: alinesno-infra-base-identity-authentication
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3309/dev_alinesno_infra_base_identity_v100?serverTimezone=GMT%2B8&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: adminer
  data:
    redis:
      database: 1
      host: 127.0.0.1
      port: 6379
#      password: aip@local
      timeout: 10s
      lettuce:
        pool:
          max-active: 200
          max-wait: -1ms
          max-idle: 10
          min-idle: 0
  devtools:
    restart:
      enabled: true

sa-token:
  sso:
    allow-url: "*"
    ticket-timeout: 300
    is-http: true
  is-print: false
  sign:
    secret-key: kQwIOrYvnXmSDkwEiFngrKidMcdrgKor

forest:
  log-enabled: false
